fix #115 for mysql 8.0.0
krowinski/php-mysql-replication pull request #116
Opened 2024-05-05 00:21 UTC by hetao29

2024-05-08 07:34 UTC, krowinski commented
hi tx for contribution pls run `composer cs:fix` to fix code style

2024-05-08 07:37 UTC, krowinski requested changes
Fix tests 
1) MySQLReplication\Tests\Unit\Repository\MySQLRepositoryTest::testShouldGetVersion
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'foobar1[23](https://github.com/krowinski/php-mysql-replication/pull/116/checks#step:9:24)'
+''

2024-11-18 08:28 UTC, cyppe commented
Any status of this PR or is there some other php 8.4 fixes in the works?

2024-11-18 08:39 UTC, hetao29 commented
> Any status of this PR or is there some other php 8.4 fixes in the works?

My project used this pr in product env.

2025-04-19 20:56 UTC, cyppe commented
@krowinski now with more mysql versions in test suite, maybe this has a chance to be tested and (maybe) merged?

2025-04-20 06:21 UTC, krowinski commented
@cyppe resolve conflict pls

2025-04-20 06:21 UTC, krowinski requested changes

2025-04-20 06:21 UTC, krowinski commented on composer.json
> +  "name": "hetao29/php-mysql-replication",
change back :)

2025-04-20 06:21 UTC, krowinski commented on src/MySQLReplication/BinLog/BinLogSocketConnect.php
> +			if(version_compare($this->repository->getVersion(),"8.4.0")>=0){
use single quotes  

run `composer cs:fix`

2025-04-23 14:38 UTC, krowinski commented
tests are failing 

There were 2 failures:

1) MySQLReplication\Tests\Unit\BinaryDataReader\BinaryDataReaderTest::testShouldReadInt64
Failed asserting that -72057589759737856 is identical to '-72057589759737856'.

/home/runner/work/php-mysql-replication/php-mysql-replication/tests/Unit/BinaryDataReader/BinaryDataReaderTest.php:138

2) MySQLReplication\Tests\Unit\BinaryDataReader\BinaryDataReaderTest::testShouldPack64bit
Failed asserting that 9[22](https://github.com/krowinski/php-mysql-replication/actions/runs/14571121836/job/40871007056?pr=116#step:9:23)3372036854775807 is identical to '92[23](https://github.com/krowinski/php-mysql-replication/actions/runs/14571121836/job/40871007056?pr=116#step:9:24)372036854775807'.

/home/runner/work/php-mysql-replication/php-mysql-replication/tests/Unit/BinaryDataReader/BinaryDataReaderTest.php:190

FAILURES!
Tests: 131, Assertions: 666, Failures: 2.

2025-04-25 12:16 UTC, krowinski requested changes

2025-04-25 12:16 UTC, krowinski commented on src/MySQLReplication/BinaryDataReader/BinaryDataReader.php
> +		}
Its better to return always string here

2025-04-25 12:16 UTC, krowinski commented on src/MySQLReplication/BinaryDataReader/BinaryDataReader.php
> +		}
same here

2025-04-26 00:54 UTC, hetao29 commented on src/MySQLReplication/BinaryDataReader/BinaryDataReader.php
> +		}
The PDO or MysqlNd default return string( big than PHP_INT_MAX) and int(less than PHP_INT_MIN) ，but in the end, you decide.

2025-05-10 08:43 UTC, cyppe commented on src/MySQLReplication/BinaryDataReader/BinaryDataReader.php
> +		}
Looks like you are really close to getting this done, @krowinski maybe you can be the tie breaker and just say how you want it to get this rolling? Would be awesome to get Mysql 8.4 support rolling.

2025-05-19 01:36 UTC, hetao29 commented
At present, the main problem is that there are some problems with the test cases in tests. I have taken a look at it and it is quite complicated. I would like to ask you to solve it~~

2025-09-24 05:43 UTC, closed without merging